# Generated by Django 3.2.9 on 2022-07-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('cal', '0002_auto_20220716_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.tor'),
            preserve_default=False,
        ),
    ]
